name: RestaurantSaas
description: Restaurant Saas flutter app by Pietech Solution

version: 1.0.17+18

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  country_list_pick: ^1.0.1+2
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+3
  async_loader: ^0.1.2
  flutter_swiper: ^1.1.6
  google_maps_flutter: ^0.5.25+3
  location: ^3.0.2
  geocoder: ^0.2.1
  image_picker: ^0.6.5
  onesignal_flutter:
  intl: ^0.16.1
  toast: ^0.1.5
  sentry: ^3.0.1
  flutter_datetime_picker: 1.4.0
  flutter_map_picker: ^0.1.2
  flutter_credit_card: ^0.1.3
  url_launcher: ^5.4.10
  getwidget: ^1.2.4
  stripe_payment: ^1.0.8
  webview_flutter: ^0.3.22+1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/i18n/en.json
    - lib/assets/i18n/es.json
    - lib/assets/logos/logo.png

    - lib/assets/imgs/chicken.png
    - lib/assets/imgs/na.jpg
    - lib/assets/imgs/man.png
    - lib/assets/imgs/menu.png
    - lib/assets/imgs/banner.png
    - lib/assets/imgs/logo.png
    - lib/assets/imgs/cart.png

    - lib/assets/bgImgs/background.png
    - lib/assets/bgImgs/confirmedbg.png
    - lib/assets/bgImgs/coverbg.png
    - lib/assets/bgImgs/loginbg.png

    - lib/assets/headers/menu.png

    - lib/assets/icon/about.png
    - lib/assets/icon/addbtn.png
    - lib/assets/icon/carte.png
    - lib/assets/icon/favorite.png
    - lib/assets/icon/marker.png
    - lib/assets/icon/loginIcon.png
    - lib/assets/icon/minus.png
    - lib/assets/icon/orderHistory.png
    - lib/assets/icon/qmark.png
    - lib/assets/icon/settings.png
    - lib/assets/icon/spoon.png
    - lib/assets/icon/resto.png

    - lib/assets/icon/spinner.gif
    - lib/assets/icon/location1.png

    - lib/assets/icons/auth.png
    - lib/assets/icons/arrowback.png
    - lib/assets/icons/tickmark.png
    - lib/assets/icons/location.png
    - lib/assets/icons/locationon.png
    - lib/assets/icons/cart.png
    - lib/assets/icons/drawer.png
    - lib/assets/images/banner.png
    - lib/assets/images/pizza.png
    - lib/assets/icons/shop.png
    - lib/assets/icons/free.png
    - lib/assets/images/dominos.png
    - lib/assets/icons/veg.png
    - lib/assets/icons/sale.png
    - lib/assets/images/cod.png
    - lib/assets/images/cash.png
    - lib/assets/images/stripe.png
    - lib/assets/images/thnku.png
    - lib/assets/images/user.png
    - lib/assets/icons/home.png
    - lib/assets/icons/fav.png
    - lib/assets/icons/orders.png
    - lib/assets/icons/about.png
    - lib/assets/icons/logo.png
    - lib/assets/icons/call.png
    - lib/assets/icons/mail.png
    - lib/assets/icons/locate.png
    - lib/assets/icons/tick.png
    - lib/assets/icons/camera.png
    - lib/assets/images/cod1.png
    - lib/assets/images/c.png
    - lib/assets/images/d.png
    - lib/assets/images/m.png
    - lib/assets/images/v.png
    - lib/assets/images/a.png